### ISSUE TITLE
cmon-events panic in severalnines/clustercontrol:latest

### ISSUE THREAD

**Issue by dfroberg** [severalnines/docker#5]
In latest `entrypoint.sh` on container init and manual `service cmon-events restart` inside the container;

```
Restarting cmon-events

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x503e22]

goroutine 1 [running]:
panic(0x6cfb40, 0xc42000e060)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/severalnines/cmon-events/config.initMySqlConnection()
        /var/lib/jenkins/jobs/clustercontrol-notifications/workspace/src/github.com/severalnines/cmon-events/config/config.go:284 +0x612
github.com/severalnines/cmon-events/config.GetServicesConfigs(0xc420033e28, 0x2, 0x2, 0x6b8540, 0xc42000f300)
        /var/lib/jenkins/jobs/clustercontrol-notifications/workspace/src/github.com/severalnines/cmon-events/config/config.go:39 +0x402
main.main()
        /var/lib/jenkins/jobs/clustercontrol-notifications/workspace/src/github.com/severalnines/cmon-events/cmon-events.go:51 +0x26b
```

**Comment by ashraf-s9s** [comment]
@dfroberg , this is a known issue because of the changes on default CMON configuration location in Docker image from `/etc/cmon.cnf` to `/etc/cmon.d/cmon.cnf`. I've pushed a major update which contains lots of fixes including use correct parameter when starting cmon-events. All services are now handled by supervisord.

New image is built and available in Docker Hub. I'm closing this.
